### ISSUE TITLE
Creating donut pie chart

### ISSUE THREAD

**Issue by ghost** [xyzzer/WinRTXamlToolkit#14]
Hi,
I am using WinRTXAMLToolKit for creating charts in VS2015, how can i create a donut pie chart, i could not find any sample for the same. 

Thanks,
Samarth

**Comment by xyzzer** [comment]
The simple solution is to put a background-colored circle in the center of a pie chart.
The more complicated one is to dig into the code of the pie data series and pie data point and create a derived donut pie data series and donut pie data point.
