### ISSUE TITLE
UWP : Validation

### ISSUE THREAD

**Issue by Binjaaa** [xyzzer/WinRTXamlToolkit#15]
Hey!

I want to create a value check on the value of the TextBox, but not by it's value, but by a method call.
As far as I can see, I can't overwrite the Validate method in FieldValidationHandler<T> class.

Is there a way to create a custom validation rule?
Thanks!
Binjaaa

**Comment by xyzzer** [comment]
I would take the validation code out of the toolkit and include out in your app. Then you can do anything you need. I will consider adding that extensibility as a feature, but don't depend on it.

Sent from Outlook Mobile

On Wed, Jan 6, 2016 at 11:28 AM -0800, "imre.turi" notifications@github.com wrote:

Hey!

I want to create a value check on the value of the TextBox, but not by it's value, but by a method call.

As far as I can see, I can't overwrite the Validate method in FieldValidationHandler class.

Is there a way to create a custom validation rule?

Thanks!

Binjaaa
