### ISSUE TITLE
Discontinue UWP nuget packages. Replace non-UWP ones with UWP ones.

### ISSUE THREAD

**Issue by xyzzer** [xyzzer/WinRTXamlToolkit#21]
Seems like not many people download the UWP versions of the packages and instead use the 2-year old non-UWP version. It might raise some issues for people targeting 8.1, but they can specify requirement of the 1.6.1.3 version to support 8.1. Otherwise - UWP will be the new default.

This should coincide with version 2.0 that I'm working on right now that will also have some code cleanup, method name changes (async method names ending with ~Async now) etc.

ETA - within the next week or two.

**Comment by gardnerjr** [comment]
for psuedo-backcompat you could always leave the uwp ones, but change them to have no actual code and have them have a dependency of the new/real ones.  that way anyone who already is using the uwp ones would get the changes when they update?

**Comment by xyzzer** [comment]
It's a good idea, thanks!

And it seems like I got too busy to finish the work within the ETA. I have some time tonight, so we'll see how far I can push it.

**Comment by xyzzer** [comment]
Pushed 2.0. A few changes left. Both UWP and default versions of the nuget packages have same binaries right now. I might switch to dependency solution in a later version.
