### ISSUE TITLE
How do I bind TreeView selected item to ViewModel?

### ISSUE THREAD

**Issue by nehmebilal** [xyzzer/WinRTXamlToolkit#34]
Can't find any docs and the video link is not working.

**Comment by xyzzer** [comment]
Sorry, I think they removed the video. I don't think it had the details you're looking for anyway. The sample doesn't show what you're asking about indeed, but you should be able to bind the `SelectedItem` property of the `TreeView` to your view model. If you want to bind the selection state of each tree node to the node model - the visual tree debugger shows how it can be done. using the `IsSelectedBindingPath` property.

https://github.com/xyzzer/WinRTXamlToolkit/blob/master/WinRTXamlToolkit.Debugging/Views/VisualTreeView.xaml

```
    <controls:TreeView
        x:Name="treeView"
        ItemsSource="{Binding RootElements}"
        ItemTemplate="{StaticResource TreeViewItemTemplate}"
        IsSelectedBindingPath="IsSelected"
```

**Comment by nehmebilal** [comment]
Awesome thanks!
