### ISSUE TITLE
Why is parameter dynamic in Attach method.

### ISSUE THREAD

**Issue by mauricemarkvoort** [xyzzer/WinRTXamlToolkit#50]
Why is the `boundSelection` parameter of the Attach method in `ListViewExtensions.cs` dynamic?

This is crashing my UWP app when I have `Compile with .NET Native tool chain` checked. By removing the reflection within that method and replacing it directly with the CollectionChanged handler, it is working for me.

I am just curious.

**Comment by xyzzer** [comment]
Can't recall right now and I'm a bit too busy to investigate it, but there was a bug there in certain cases and this was a fix someone suggested. I would just use a fork of the toolkit if that fixes the problem. If you'd like to change it in the public toolkit - check the list of issues (probably still on codeplex: http://winrtxamltoolkit.codeplex.com/workitem/list/basic) and/or history for this file to find what the original problem was.

**Comment by mauricemarkvoort** [comment]
Thanks for the quick answer. 
Will just create a fork for now and change it in there.

For more information: https://docs.microsoft.com/en-us/dotnet/framework/net-native/reflection-and-net-native
