### ISSUE TITLE
Caliburn micro compatibility

### ISSUE THREAD

**Issue by MkazemAkhgary** [xyzzer/WinRTXamlToolkit#54]
does this work with caliburn micro?

I have a `LineSeries` called `Chart`. how do I make this connection from shell view model to shell view?

        public class ChartItem
        {
            public TimeSpan Value{ get; set; }
            public DateTime Time { get; set; }
        }

        BindableCollection<ChartItem> Chart { get; } = new BindableCollection<ChartItem>();

but adding items to Chart does not show in `LineSeries`.

**Comment by xyzzer** [comment]
I've never tested with Caliburn micro, but I vaguely remember that there
were some issues using bindings with the chart data. YMMV. If you see
issues - consider fixing them in the source and submitting a PR.

**Comment by MkazemAkhgary** [comment]
It works! I just had to write it correctly. @xyzzer 

        <rt:Chart>
            <rt:Chart.Series>
                <rt:LineSeries ItemsSource="{Binding MyChart}"
                               DependentValuePath="Value.Milliseconds" IndependentValuePath="Time"/>
            </rt:Chart.Series>
        </rt:Chart>

Also `BindableCollection` causes a lot of GC pressure. `ObservableCollection` works like a charm, and `List` throws exception for some reason.

        private ObservableCollection<ChartItem> _myChart = new ObservableCollection<ChartItem>();
        public ObservableCollection<ChartItem> MyChart
        {
            get { return _myChart; }
            set
            {
                _myChart = value;
                NotifyOfPropertyChange(() => MyChart);
            }
        }

**Comment by MkazemAkhgary** [comment]
@xyzzer is there any documentation or tutorial on how to work with `LineSerier`? 

I really liked your tool, but I have no idea what each property does. I couldn't find documentation anywhere so I'm just doing trial and error. its becoming frustrating :(

thanks in advance.
