### ISSUE TITLE
HorizontalScrollViewerStyle static resource in Sample application

### ISSUE THREAD

**Issue by bcnzer** [xyzzer/WinRTXamlToolkit#6]
WinRTXamlToolkit.Sample.UWP has two locations where the ScrollViewer has a style defined as HorizontalScrollViewerStyle. Unfortunately it's not defined anywhere and will cause a XAML runtime error when you try to run it. 

The two place it's used is in ParallaxBackgroundBehaviorTestView and TextBoxValidationTestView.

My workaround in the meantime is to simply remove the style reference.

**Comment by xyzzer** [comment]
Thanks for reporting. Fixed.
